### ISSUE TITLE
May I have your contact information?

### ISSUE THREAD

**Issue by chensuixin** [panpp-git/cResFreq#1]
I am very interested in your subject, but I have some questions when running the model. Can you give me your contact information?

**Comment by panpp-git** [comment]
Thx for pointing it out. I have checked the codes, adding some "lost" files and deleting some draw-plotting sentences. The training process works now. And, Email for you: panpp3@mail2.sysu.edu.cn

**Comment by panpp-git** [comment]
> I am very interested in your subject, but I have some questions when running the model. Can you give me your contact information?

Thx for pointing it out. I have checked the codes, adding some "lost" files and deleting some draw-plotting sentences. The training process works now. For Matlab codes, a readme file is added for each folder.  And, Email for you: panpp3@mail2.sysu.edu.cn
